### ISSUE TITLE
Installation breaks `ember-sinon`

### ISSUE THREAD

**Issue by jamesdixon** [yratanov/ember-cli-mock-socket#3]
Hi again,

Not sure if you've ran into this, but I have `ember-sinon` installed to use Sinon for spying. Unfortunately, after installing `ember-cli-mock-socket`, my tests can no longer find Sinon. Here's the specific error:

```
Error: Could not find module `sinon` imported from `business/tests/acceptance/authentication-test`
    at requireFrom (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:119:13)
    at reify (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:106:22)
    at mod.state (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:149:17)
    at tryFinally (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:30:14)
    at requireModule (http://localhost:7357/assets/vendor-fef92444fcee2380784bf5f81617ce31.js:148:5)
    at Object.TestLoader.require (http://localhost:7357/assets/test-loader-f0f109fd1752a6914c1c9dab886e3f4d.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:7357/assets/test-loader-f0f109fd1752a6914c1c9dab886e3f4d.js:21:18)
    at Function.TestLoader.load (http://localhost:7357/assets/test-loader-f0f109fd1752a6914c1c9dab886e3f4d.js:40:24)
    at http://localhost:7357/assets/test-support-223b96cf086e0f87a8be49e193a89529.js:14835:16
```

Removing `ember-cli-mock-socket` fixes the issue.

Have you run into this?

Best,
James

**Comment by yratanov** [comment]
humm... it's weird. This addon does nothing except of adding bower package. Have you tried to just add https://github.com/thoov/mock-socket via bower?
